### ISSUE TITLE
TypeError: The header content contains invalid characters

### ISSUE THREAD

**Issue by Yukaii** [puraku/client#2]
```
TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
```

WTF 系列，OAuth 都設定好了，只差呼叫 API endpoint，卻又出這種問題 = =，找找看要怎麼修，如果無法就又要重刻 OAuth 了 Zzz

**Comment by Yukaii** [comment]
結果是在進行重新封裝時參數搞錯...沒有包成 option 的參數最難搞啦

>  THE console.log DEBUG 法，被 ES6 慣壞惹
